trigger:
  paths:
    include:
      - **/*.tf
    exclude:
      - azure-pipelines-backend.yml
variables:
- group: Terraform_Variable
pool:
  vmImage: ubuntu-latest
parameters:
#  - name: adminpassword
#    displayName: Admin_Password
#    type: string
#    default:
 - name: execlevel
   displayName: Execution Level
   type: string
   default: plan
   values:
     - plan
     - apply
     - destroy
 - name: platform
   displayName: Platform deploy
   type: string
   default: linux
   values:
     - linux
     - windows

stages:
  - stage: tfvalidate
    condition: eq ('${{parameters.execlevel}}' , 'plan')
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: 'Install Latest Terraform'
            inputs:
              terraformVersion: 'latest'
          - checkout: self
            displayName: 'Checkout repository'
          - task: TerraformCLI@0
            displayName: 'initialise Terraform'
            timeoutInMinutes: 3
            inputs:
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)'
              backendType: 'azurerm'
              backendServiceArm: 'Free_Trial'
              ensureBackend: true
              backendAzureRmResourceGroupName: '$(storage_rg_name)'
              backendAzureRmResourceGroupLocation: '$(location)'
              backendAzureRmStorageAccountName: '$(storage_account_name)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformCLI@0
            displayName: 'Validate Terraform'
            inputs:
              command: 'validate'
              workingDirectory: '$(Build.SourcesDirectory)'
          - task: TerraformCLI@0
            displayName: 'Plan Terraform'
            inputs:
              command: 'plan'
              environmentServiceName: 'Free_Trial'
              commandOptions: '--target=module.${{ parameters.platform }}_vm -var resource_group_name=$(resource_group_name) -out=terraform.tfplan'
              publishPlanResults: 'Terraform_plan'

  - stage: tfdeploy
    condition: eq ('${{parameters.execlevel}}' , 'apply')
    jobs:
     - job: apply
       steps:
         
          - task: TerraformCLI@0
            displayName: 'initialise Terraform'
            inputs:
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)'
              backendType: 'azurerm'
              backendServiceArm: 'Free_Trial'
              backendAzureRmResourceGroupName: '$(storage_rg_name)'
              backendAzureRmStorageAccountName: '$(storage_account_name)'
          - task: TerraformCLI@0
            displayName: 'Plan Terraform'
            inputs:
              command: 'plan'
              environmentServiceName: 'Free_Trial'
              commandOptions: '--target=module.${{ parameters.platform }}_vm -var resource_group_name=$(resource_group_name) -out=terraform.tfplan'
              publishPlanResults: 'Terraform_plan'
          - task: TerraformCLI@0
            displayName: 'Import Terraform'
            continueOnError: true
            inputs:
              command: 'import'
              workingDirectory: '$(Build.SourcesDirectory)'
              environmentServiceName: 'Free_Trial'
              resourceAddress: 'azurerm_resource_group.rg'
              resourceId: '/subscriptions/3bc9efe9-3af6-45ac-93a2-a2901d8838ae/resourceGroups/$(resource_group_name)-rg'

          - task: TerraformCLI@0
            displayName: 'Apply Terraform'
            continueOnError: true
            inputs:
              command: 'apply'
              environmentServiceName: 'Free_Trial'
              workingDirectory: '$(Build.SourcesDirectory)'
              commandOptions: '--target=module.${{ parameters.platform }}_vm -var resource_group_name=$(resource_group_name)'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**azurekey.pem'  # Specify the file to copy
              TargetFolder: '$(Build.ArtifactStagingDirectory)' 
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'azuredata'
            
  - stage: tfdestroy
    condition: eq ('${{parameters.execlevel}}' , 'destroy')
    jobs:
     - job: destroy
       steps:
          - task: TerraformCLI@0
            displayName: 'initialise Terraform'
            inputs:
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)'
              backendType: 'azurerm'
              backendServiceArm: 'Free_Trial'
              backendAzureRmResourceGroupName: '$(storage_rg_name)'
              backendAzureRmStorageAccountName: '$(storage_account_name)'
          - task: TerraformCLI@0
            displayName: 'destroy Terraform'
            timeoutInMinutes: 5
            inputs:
              command: 'destroy'
              environmentServiceName: 'Free_Trial'
              workingDirectory: '$(Build.SourcesDirectory)'
              commandOptions: '--target=module.${{ parameters.platform }}_vm'
