# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool:
  vmImage: ubuntu-latest
parameters:
 - name: execlevel
   displayName: Execution Level
   type: string
   default: read
   values:
     - create
     - read
     - update
     - delete
     - drop
 - name: var_group
   displayName: Variable Group Name
   type: string
   default: Variable_Group
 - name: variable
   displayName: Variable Name
   type: string
   default: Variable1
 - name: value
   displayName: Variable Value 
   type: string
   default: TEST
 - name: secret
   displayName: Is Secret? 
   type: boolean
   default: false

stages:
  - stage: Group_Create
    condition: eq ('${{parameters.execlevel}}' , 'create')
    jobs:
      - job: Create
        steps:
          - task: AzureCLI@2
            displayName: 'create variable group'
            inputs:
              azureSubscription: 'Free_Trial'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
                group_id=$(az pipelines variable-group list --detect true --query "[?name=='${{ parameters.var_group }}'].id" --output tsv)
                if [ -z "$group_id" ]; then
                  az pipelines variable-group create --detect true --authorize true --name ${{ parameters.var_group }} --description "Variables for my Variable group" --variables ${{ parameters.variable }}=${{ parameters.value }} --output yaml
                else
                  az pipelines variable-group variable create --detect true --group-id $group_id --name ${{ parameters.variable }} --value ${{ parameters.value }} --secret ${{ parameters.secret }} --output table
                fi
  - stage: Read_Variable
    condition: eq ('${{parameters.execlevel}}' , 'read')
    jobs:
      - job: read
        steps:
          - task: AzureCLI@2
            displayName: 'Read variable'
            inputs:
              azureSubscription: 'Free_Trial'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
                echo "#### List the Variables in Library ####"
                az pipelines variable-group list --detect true --top 3 --query-order Asc --output table
                group_id=$(az pipelines variable-group list --detect true --query "[?name=='${{ parameters.var_group }}'].id" --output tsv)
                variable=$(az pipelines variable-group show --detect true --group-id $group_id --output json | jq -cr '.variables."${{ parameters.variable }}".value')
                echo -e ${{ parameters.var_group }} "Conatins Variable name-"${{ parameters.variable }} "with value is \n "${variable}
  - stage: Update_Variable
    condition: eq ('${{parameters.execlevel}}' , 'update')
    jobs:
      - job: update
        steps:
          - task: AzureCLI@2
            displayName: 'Update Variable in variable group'
            inputs:
              azureSubscription: 'Free_Trial'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
                group_id=$(az pipelines variable-group list --detect true --query "[?name=='${{ parameters.var_group }}'].id" --output tsv)
                az pipelines variable-group variable update --detect true --group-id $group_id --name ${{ parameters.variable }} --value ${{ parameters.value }} --secret ${{ parameters.secret }} --output yaml
  - stage: Delete_Variable
    condition: eq ('${{parameters.execlevel}}' , 'delete')
    jobs:
      - job: delete
        steps:
          - task: AzureCLI@2
            displayName: Delete Variable from Variable Group
            inputs:
              azureSubscription: 'Free_Trial'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
                group_id=$(az pipelines variable-group list --detect true --query "[?name=='${{ parameters.var_group }}'].id" --output tsv)
                az pipelines variable-group variable delete --detect true --group-id $group_id --name ${{ parameters.variable }} --yes
                
  - stage: Group_Delete
    condition: eq ('${{parameters.execlevel}}' , 'drop')
    jobs:
      - job: drop
        steps:
          - task: AzureCLI@2
            displayName: Delete Variable Group
            inputs:
              azureSubscription: 'Free_Trial'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                export AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
                gr_id=$(az pipelines variable-group list --detect true --group-name ${{ parameters.var_group }} --output table | awk '{ print $1}' | tail -1)
                az pipelines variable-group delete --detect true --group-id $gr_id --yes
# # Other Possible commands refer here
# https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=azure-devops-cli#show-details-for-a-variable-group
# az devops configure --use-git-aliases true
# az devops configure --defaults organization=$(System.CollectionUri) project=$(System.TeamProject)
# Below are Update Variable Group Name and Description
# az pipelines variable-group update --detect true --group-id $gr_id --name Updated-Variables --description "Updated Variables for pipeline" --output table
#az pipelines variable-group variable update --detect true --group-id $gr_id --new-name ${{ parameters.new_variable }} --name ${{ parameters.variable }} --value ${{ parameters.value }} --secret ${{ parameters.secret }} --output yaml
