stages:
  - choose_operation
  - execute_operation
variables:
  OPERATION:
    value: "create" # Default operation, can be overridden
    options:
      - "create"
      - "read"
      - "update"
      - "delete"
      - "drop"
    description: "Enter Execution policy"
  var_group:
    value: "Test"
    description: "Enter Variable Group Name"
  variable:
    value: "Name"
    description: "Enter Variable Name"
  value:
    value: "app"
    description: "Enter Value Value"
  secret:
    value: "false"
    options:
      - "false"
      - "true"
    description: "Is Secret"

choose_operation:
  stage: choose_operation
  script:
    - echo "Selected operation $OPERATION"
  only:
    - main
execute_operation:
  stage: execute_operation
  script:
    - |
      az config set extension.use_dynamic_install=yes_without_prompt
      az devops configure -d organization=https://dev.azure.com/safiquddinkhan project=onestop
      export AZURE_DEVOPS_EXT_PAT="${AccessToken}" 
      group_id=$(az pipelines variable-group list --query "[?name=='${var_group}'].id" -o tsv)
      if [ "$OPERATION" == "create" ]; then
        if [ -z "$group_id" ]; then
          echo "az pipelines variable-group create --authorize true --name ${var_group} \
          --description 'Variables for my Variable group' --variables ${variable}=${value} -o yaml"
          az pipelines variable-group create --authorize true --name ${var_group} \
          --description "Variables for my Variable group" --variables ${variable}=${value} -o yaml
        else
          echo "az pipelines variable-group variable create --id ${group_id} \
          --name ${variable} --value ${value} --secret ${secret} -o table"
          az pipelines variable-group variable create --id ${group_id} --name ${variable} \
          --value ${value} --secret ${secret} -o table
        fi
      elif [ "$OPERATION" == "read" ]; then
        echo "group id= ${group_id}"
        az pipelines variable-group list --top 3 --query-order Asc -o table
        data=$(az pipelines variable-group show --id ${group_id} -o json | jq -cr \
        .variables.${variable}.value)
        echo "az pipelines variable-group show --id ${group_id} -o json | jq -cr \
        .variables.${variable}.value)"
        echo -e ${var_group} "Conatins Variable-"${variable} "with value is \n"$data
      elif [ "$OPERATION" == "update" ]; then
        echo "az pipelines variable-group variable update --id ${group_id} --name ${variable} \
        --value ${value} --secret ${secret} -o yaml"
        #use --new-name for change the name of the variable.
        az pipelines variable-group variable update --id ${group_id} --name ${variable} \
        --value ${value} --secret ${secret} -o yaml
      elif [ "$OPERATION" == "delete" ]; then
        echo "az pipelines variable-group variable delete --id ${group_id} \
        --name ${variable} -y"
        az pipelines variable-group variable delete --id ${group_id} --name ${variable} -y
      elif [ "$OPERATION" == "drop" ]; then
        echo "az pipelines variable-group delete --id ${group_id} -y"
        az pipelines variable-group delete --id ${group_id} -y
      else
        echo "Invalid operation selected" 
        exit 1
      fi
      az devops logout || echo "az devops logout unsuccessful"
      # If previously az login then az devops logout
  only:
    - main
  needs: # previous stage to succeed before it can run.
    - job: choose_operation 
