stages:
  - choose_operation
  - execute_operation

variables:
  OPERATION:
    value: "read" # Default operation, can be overridden
    options:
      - "create"
      - "read"
      - "update"
      - "delete"
    description: "Enter Execution policy"
  var_group:
    value: "Variable_Group"
    description: "Enter Variable Group Name"
  variable:
    value: "Variable1"
    description: "Enter Variable Name"
  value:
    value: "TEST"
    description: "Enter Value Value"
  secret:
    value: "false"
    description: "Is Secret"

choose_operation:
  stage: choose_operation
  script:
    - echo "Selected operation $OPERATION"
  only:
    - master  # Adjust the branch or trigger conditions as needed

execute_operation:
  stage: execute_operation
  script:
    - |
      az config set extension.use_dynamic_install=yes_without_prompt
      az devops configure -d organization=https://dev.azure.com/safiquddinkhan project=onestop
      export AZURE_DEVOPS_EXT_PAT="${AccessToken}" 
      group_id=$(az pipelines variable-group list --query "[?name=='${var_group}'].id" --output tsv)
      if [ "$OPERATION" == "create" ]; then
        if [ -z "$group_id" ]; then
          az pipelines variable-group create --authorize true --name ${var_group} --description "Variables for my Variable group" --variables ${variable}=${value} --output yaml
        else
          az pipelines variable-group variable create --group-id ${group_id} --name ${variable} --value ${value} --secret ${secret} --output table
        fi
      elif [ "$OPERATION" == "read" ]; then
        az pipelines variable-group list --top 3 --query-order Asc --output table
        data=$(az pipelines variable-group show --group-id ${group_id} --output json | jq -cr .variables.${variable}.value)
        echo -e ${var_group} "Conatins Variable name-"${variable} "with value is \n " $data
      elif [ "$OPERATION" == "update" ]; then
        az pipelines variable-group variable update --group-id ${group_id} --name ${variable} --value ${value} --secret ${secret} --output yaml
      elif [ "$OPERATION" == "delete" ]; then
        az pipelines variable-group variable delete --group-id ${group_id} --name ${variable} --yes
      else
        echo "Invalid operation selected" 
        exit 1
      fi
      az devops logout || echo "az devops logout unsuccessful"
      
  only:
    - master
  # rules:
  #   - if: '$CI_JOB_SUCCESS == "true"'
  #   - when: on_success  # Run this job only if the previous job succeeds
      # az devops login --organization "https://dev.azure.com/safiquddinkhan"
      # az config set extension.use_dynamic_install=yes_without_prompt