name: Terraform Pipeline

on:
  push:
    branches:
      - master # Specify the branch you want to trigger this pipeline on

jobs:
  setup_backend:
    runs-on: sfq_win
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform Backend
        run: |
          terraform --version
          terraform init
          terraform validate
          terraform plan -out=backend.tfplan
          terraform import azurerm_resource_group.rg "/subscriptions/3bc9efe9-3af6-45ac-93a2-a2901d8838ae/resourceGroups/${{ env.TF_VAR_BE_RG_NAME }}-rg"
          terraform apply -var="resource_group_name=${{ env.TF_VAR_BE_RG_NAME }}" -var="storage_account_name=${{ env.TF_VAR_BE_STORAGE_ACCOUNT }}" --auto-approve

        env:
          TF_VAR_BE_RG_NAME: ${{ secrets.TF_VAR_BE_RG_NAME }}
          TF_VAR_BE_STORAGE_ACCOUNT: ${{ secrets.TF_VAR_BE_STORAGE_ACCOUNT }}

      - name: Upload Terraform State
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: .terraform/
          path: terraform.tfstate

  tfvalidate:
    needs: setup_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

  tfplan:
    needs: setup_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init -backend-config="resource_group_name=${{ env.TF_VAR_BE_RG_NAME }}" -backend-config="storage_account_name=${{ env.TF_VAR_BE_STORAGE_ACCOUNT }}"

      - name: Create Terraform Plan
        run: |
          terraform plan --target=module.${{ env.TF_VAR_PLATFORM }}_vm -var="resource_group_name=${{ env.TF_VAR_RG_NAME }}" -out=terraform.tfplan
          terraform import azurerm_resource_group.rg "/subscriptions/3bc9efe9-3af6-45ac-93a2-a2901d8838ae/resourceGroups/${{ env.TF_VAR_RG_NAME }}-rg"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: terraform.tfplan

  tfdeploy:
    needs: tfplan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init -backend-config="resource_group_name=${{ env.TF_VAR_BE_RG_NAME }}" -backend-config="storage_account_name=${{ env.TF_VAR_BE_STORAGE_ACCOUNT }}"

      - name: Deploy Infrastructure
        run: |
          terraform import azurerm_resource_group.rg "/subscriptions/3bc9efe9-3af6-45ac-93a2-a2901d8838ae/resourceGroups/${{ env.TF_VAR_RG_NAME }}-rg"
          terraform apply --target=module.${{ env.TF_VAR_PLATFORM }}_vm -var="resource_group_name=${{ env.TF_VAR_RG_NAME }}" --auto-approve

  tfdestroy:
    needs: tfplan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init -backend-config="resource_group_name=${{ env.TF_VAR_BE_RG_NAME }}" -backend-config="storage_account_name=${{ env.TF_VAR_BE_STORAGE_ACCOUNT }}"

      - name: Destroy Infrastructure
        run: terraform destroy --target=module.${{ env.TF_VAR_PLATFORM }}_vm --auto-approve
# GitHub self-hosted runner package- https://github.com/actions/runner/releases
# ./config.sh --url https://github.com/yourusername/yourrepository --token YOUR-PAT --name NAME-OF-YOUR-RUNNER --work WORK-DIRECTORY
# start the runner
# ./svc.sh install
# ./svc.sh start

